---
- name: Test new role from within this playbook
  hosts: vectortile
  gather_facts: false
  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: local.osm.vectortile
        tasks_from: main.yml
